[package]
name = "bevy_boids"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
#bevy_rts_camera = "0.9"
bevy_panorbit_camera = "0.23.0"
bevy_rapier3d = "0.29.0"
bevy_dev_tools = "0.15.3"
bevy_egui = "0.33"
#noise = "0.9.0"